# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu_creat_doc.har
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
# 改名是为了防止用例执行时候执行了TestCaseMubuLogin
from testcases.mubu_login_test import TestCaseMubuLogin as MubuLogin

import pytest
from httprunner import Parameters

class TestCaseMubuCreatDoc(HttpRunner):
    @pytest.mark.parametrize("param", Parameters({
        "title": ["demo1", "demo2"],
        "user1": ["111", "222"],
        "phone-password": [["1", "2"], ["3", "4"]],
    }),)
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("creat new doc").verify(False)
        .base_url("https://${host1}")
        .variables(**{"host1": "api2.mubu.com",
                      "phone": "18710748230",
                      "password": "123456", 
                      "memberid": "${gen_memeberid()}"})
    )

    teststeps = [
        Step(RunTestCase("login mubu").with_variables(phone="18710748230", password="123456").call(MubuLogin).export(*["unreadCount"])),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("/v3/api/user/profile")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "unreadCount": "'${unreadCount}'",
                    "Content-Length": "0",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "36b69f65-6593-4beb-8cd6-8085c5366931",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get")
            .post("/v3/api/list/get")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "58",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "9579260e-0080-4965-9e33-48a0632fe48d",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {"folderId": 0, "sort": "time", "keywords": "", "source": "home"}
            )
            .validate()
            # 返回状态等于200
            .assert_equal("status_code", 200)
            # 返回的header的content-type值是application/json;charset=UTF-8
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("/v3/api/list/item_count")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "30",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "66790345-9de9-4e98-9c10-38158e23a545",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "122196df-0f64-49f6-9f60-d72c7b50b47c",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "0dade813-e90c-4e1d-b509-ccd1af1460a4",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "12",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "3d70f39c-bf35-4ad7-a387-5e59b2872633",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("/v3/api/advertisement/get")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "10",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "2af0571a-cd75-4b42-9a30-f23b328a7cc9",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("/v3/api/list/item_count")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "30",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "66790345-9de9-4e98-9c10-38158e23a545",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "10",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "36c9b11e-d981-465c-92f5-6532ed878ac4",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("/v3/api/list/create_doc")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "25",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "47f625f3-35b2-45cd-bc82-f13ba6086477",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            # 提取接口的返回 > 参数关联的第一步是提取参数，extract方法在请求之后提取，一般紧挨着body。
            .extract()
            # 提取body体id值,传入变量docId， body中按层级提取，字典按.提取，列表按[]索引提取，具体看官网。
            .with_jmespath("body.data.id", "docId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("/v3/api/list/item_count")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "30",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "3a0c7ad0-02a6-40b1-b65a-d246fc1397b3",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("/v3/api/user/current_level")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "29",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "090dd6da-e498-4ead-8dd6-199dc9409fef",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("/v3/api/document/edit/get")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "37",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "eb0dd6dd-4bbc-4448-9308-f4074a21dc70",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "${docId}", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "29",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "9f13e0bc-5b86-443d-adab-de64054e561f",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("/v3/api/colla/register")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "93ec8a43-7dc0-41a0-b0b5-5fa46ef6e422",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("/v3/api/refer/node/count")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "29",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "8fd957bc-85d7-487c-975a-8c880ce54497",
                    "version": "3.0.0.21328",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "${docId}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://${host1}/v3/api/colla/members")
            .with_params(**{"memberId": "${memberid}", "documentId": "${docId}"})
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Accept": "*/*",
                    "Access-Control-Request-Method": "GET",
                    "Access-Control-Request-Headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "Origin": "https://mubu.com",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/octet-stream")
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("/v3/api/colla/members")
            .with_params(**{"memberId": "${memberid}", "documentId": "${docId}"})
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Request-Id": "members:${memberid}:1618021813247",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "c9818f23-e9b5-4a07-95e6-a290de84ca12",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("/v3/api/colla/message")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "514",
                    "Member-Id": "${memberid}",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Request-Id": "MESSAGE:11623951:${memberid}:3",
                    "x-request-id": "6aa726ba-9264-425c-a52f-23fd36b2f28e",
                    "version": "3.0.0",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:11623951:${memberid}:3",
                    "token": "${docId}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docId}",
                            "version": 0,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "${title}",
                                    "original": "dem",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "52",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "x-request-id": "280cf226-fbd4-4c1c-8963-edc56acc0137",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "${docId}", "keywords": "${title}", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .with_variables(nodeid="${gen_nodeid()}")
            .post("/v3/api/colla/message")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "655",
                    "Member-Id": "${memberid}",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Request-Id": "MESSAGE:11623951:${memberid}:5",
                    "x-request-id": "63014974-2ace-4544-a9a1-768cdccd3cd8",
                    "version": "3.0.0",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:11623951:${memberid}:5",
                    "token": "${docId}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docId}",
                            "version": 1,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "${nodeid}",
                                                "text": "",
                                                "modified": 1618021815429,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "${nodeid}",
                                                "text": "<span>1</span>",
                                                "modified": 1618021815856,
                                            },
                                            "original": {
                                                "id": "${nodeid}",
                                                "text": "",
                                                "modified": 1618021815429,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("/v3/api/colla/message")
            .with_headers(
                **{
                    "host1": "${host1}",
                    "Connection": "keep-alive",
                    "Content-Length": "655",
                    "Member-Id": "${memberid}",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "data-unique-id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Accept": "application/json, text/plain, */*",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTE2MjM5NTEiLCJleHAiOjE2MjA2MTMxMTEsImlhdCI6MTYxODAyMTExMX0.vb25B05BHW2VyNB6tlW58F3eVkKnnoQXvc7H-XZIt2jfFisYO4N5NPYAMLT4b5-4XVyIIDcsqaMW5i_OD9Ahyw",
                    "Request-Id": "MESSAGE:11623951:${memberid}:7",
                    "x-request-id": "ea24cf8e-91b7-4d8c-81e7-6f1da9eabdc5",
                    "version": "3.0.0",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-site",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:11623951:${memberid}:7",
                    "token": "${docId}",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "${docId}",
                            "version": 2,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "VipSL6S5gz",
                                                "text": "",
                                                "modified": 1618021816323,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                },
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "VipSL6S5gz",
                                                "text": "<span>2</span>",
                                                "modified": 1618021816562,
                                            },
                                            "original": {
                                                "id": "VipSL6S5gz",
                                                "text": "",
                                                "modified": 1618021816323,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreatDoc().test_start()
