# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\mubu_login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "Host": "mubu.com",
                    "Connection": "keep-alive",
                    "Content-Length": "47",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Origin": "https://mubu.com",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://mubu.com/login/password",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "data_unique_id=5af8ec14-0e06-45fb-948e-5852d15f593a; _ga=GA1.2.575825054.1617539185; _gid=GA1.2.961331060.1617973416; reg_entrance=https%3A%2F%2Fmubu.com%2F; language=en-US; country=US; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1617805446,1617820067,1617981171,1618017226; csrf_token=2ebd2cd9-e587-47d4-b8e3-6bb81d9fe9ce; SESSION=30786ff7-4a20-4a5c-b5aa-9d56f3586db4; _gat=1; reg_prepareId=178b9ae33da-178b9ae33d3-4763-bcdf-9510a0eb4440; reg_focusId=5247c4c4-c1ff-4763-bcdf-178b9ae36b3; SLARDAR_WEB_ID=8d09bf6a-a457-4c0e-a070-fd54f2c2279f; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1618022906",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "5af8ec14-0e06-45fb-948e-5852d15f593a",
                    "_ga": "GA1.2.575825054.1617539185",
                    "_gid": "GA1.2.961331060.1617973416",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "language": "en-US",
                    "country": "US",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1617805446,1617820067,1617981171,1618017226",
                    "csrf_token": "2ebd2cd9-e587-47d4-b8e3-6bb81d9fe9ce",
                    "SESSION": "30786ff7-4a20-4a5c-b5aa-9d56f3586db4",
                    "_gat": "1",
                    "reg_prepareId": "178b9ae33da-178b9ae33d3-4763-bcdf-9510a0eb4440",
                    "reg_focusId": "5247c4c4-c1ff-4763-bcdf-178b9ae36b3",
                    "SLARDAR_WEB_ID": "8d09bf6a-a457-4c0e-a070-fd54f2c2279f",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1618022906",
                }
            )
            .with_data(
                {"phone": "18710748230", "password": "123456", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
